[workspace]

resolver = "2"

members = [
    "cli",
    "ledger",
    "store"
]

[workspace.dependencies]
chrono = "0.4.31"
ciborium = "0.2.1"
colored = "2.1.0"
mockall = "0.12.1"
mockall_double = "0.3.1"
serde = "1.0.193"
termion = "3.0.0"